---
  listen_addr:
      host: 0.0.0.0
      port: 30001
  subscribers:
      - host: 127.0.0.1
        port: 30010
  metro_step_ms: 10
  voice_limit: 16
  default_level: 0.9
  speaker_positions:
      positions:
          # ~5.1
          # -
          #   - -1
          #   - 1
          #   - 2.9
          # -
          #   - 1
          #   - 1
          #   - 2.9
          # -
          #   - 0
          #   - 1
          #   - 3
          # -
          #   - 0
          #   - 1
          #   - 0
          # -
          #   - -2
          #   - 1
          #   - -1.5
          # -
          #   - 2
          #   - 1
          #   - -1.5

          #Stereo
          -
            - -1
            - 1
            - 1
          -
            - 1
            - 1
            - 1
  scenes:
    - example/01-scene.yml
