---
  listen_addr:
      host: 0.0.0.0
      port: 30001
  subscribers:
      - host: 127.0.0.1
        port: 30010
  metro_step_ms: 10
  voice_limit: 16
  default_level: 0.9
  scenes:
    - example/01-scene.yml
